#!/bin/sh
TMP=$(mktemp -t commit-msg)
grep -ve '^#' $1 >$TMP
cat $TMP >/tmp/dumpmsg

abort() {
    echo "Re-edit with:\n\n<last_git_command> -F .git/COMMIT_EDITMSG -e"
    exit 1
}

if [ "$(head -n 1 $TMP | wc -c)" -gt 50 ]; then
    echo "Summary max length is 50 cols"
    abort
fi

if [ "$(head -n 1 $TMP | tail -c -2)" == "." ]; then
    echo "Commit summary should not end with period"
    abort
fi

if [ "$(tail -c -1 $TMP)" != "" ]; then
    echo "Commit message should end with newline"
    abort
fi

if [ "$(cat $TMP | wc -l)" -gt 1 -a "$(head -n 2 $TMP | tail -n 1)" != "" ]; then
    echo "When a multiline message, the description should be separated by the message by one empty line"
    abort
fi
