#!/usr/bin/perl

use strict;
use warnings;

my %F;
while (<>) {
  while (/\b(V7_ENABLE__[^_]+(__[a-zA-Z]\S+)?)\b/g) {
    $F{$1}++;
  }
}

my $feature_defs = '';
foreach my $f(sort keys %F) {
  $feature_defs .= "#define $f 1\n";
}

print <<EOF
#if V7_BUILD_PROFILE == V7_BUILD_PROFILE_FULL
/*
 * DO NOT EDIT.
 * This file is generated by scripts/gen-features-full.pl.
 */

$feature_defs
#endif /* V7_BUILD_PROFILE == V7_BUILD_PROFILE_FULL */
EOF
