#if V7_BUILD_PROFILE == V7_BUILD_PROFILE_FULL
/*
 * DO NOT EDIT.
 * This file is generated by scripts/gen-features-full.pl.
 */

#define V7_ENABLE_Date__UTC 1
#define V7_ENABLE_Date__getters 1
#define V7_ENABLE_Date__now 1
#define V7_ENABLE_Date__parse 1
#define V7_ENABLE_Date__setters 1
#define V7_ENABLE_Date__toJSON 1
#define V7_ENABLE_Date__toLocaleString 1
#define V7_ENABLE_Date__toString 1

#endif
